//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RieltBaza.dataFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int ID_Comment { get; set; }
        public string comment1 { get; set; }
        public double star { get; set; }
        public int id_Client { get; set; }
        public Nullable<int> id_emp { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
