//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RieltBaza.dataFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class comm
    {
        public string emp_SN { get; set; }
        public string emp_FN { get; set; }
        public string emp_P { get; set; }
        public string Name { get; set; }
        public double star { get; set; }
        public string cnt_SN { get; set; }
        public string Cnt_FN { get; set; }
        public string Cnt_P { get; set; }
        public int ID_Comment { get; set; }
    }
}
