//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RieltBaza.dataFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Citys
    {
        public string Name { get; set; }
        public string SecondName { get; set; }
        public string FirstName { get; set; }
        public string Patronymic { get; set; }
        public string House { get; set; }
        public string Str_Name { get; set; }
        public string Phone { get; set; }
        public string Date_of_Birth { get; set; }
        public string Email { get; set; }
        public int ID_Emp { get; set; }
        public int ID_City { get; set; }
    }
}
