//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RieltBaza.dataFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class Objects
    {
        public int ID_Objects { get; set; }
        public Nullable<int> id_Emp { get; set; }
        public int id_Adress { get; set; }
        public int SQ_FT { get; set; }
        public Nullable<int> Room { get; set; }
        public string floot_many { get; set; }
        public Nullable<int> id_client { get; set; }
    
        public virtual Adress Adress { get; set; }
        public virtual Client Client { get; set; }
    }
}
