//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RieltBaza.dataFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class Objects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Objects()
        {
            this.Tabel = new HashSet<Tabel>();
        }
    
        public int ID_Objects { get; set; }
        public int id_Adress { get; set; }
        public int SQ_FT { get; set; }
        public int Room { get; set; }
        public int Floor { get; set; }
        public int CountFloor { get; set; }
        public string Image { get; set; }
    
        public virtual Adress Adress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tabel> Tabel { get; set; }
    }
}
