//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RieltBaza.dataFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tabel
    {
        public int ID_Tab { get; set; }
        public Nullable<int> id_Emp { get; set; }
        public Nullable<int> id_Client { get; set; }
        public Nullable<int> id_Obj { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Objects Objects { get; set; }
    }
}
